api support for attachment deletions
the-shop/StarAPI pull request #67
Opened 2017-01-26 13:05 UTC by mvoloder

API support for attachments deletion

method deletes uploaded files from local storage, but not from aws s3 storage

[Task link]http://the-shop.io:3000/projects/586016083e5bbe768349a4b0/sprints/5881d3aa3e5bbe274c5f1553/tasks/587a1e2f3e5bbe4334746f89

2017-01-26 13:26 UTC, lotar reviewed
This was supposed to be delete single attachment by ID route. Also did you test this since I don't see route definition in routes.

Just make sure this works as expected, I'll file new task for single attachment deletion

2017-01-27 13:15 UTC, lotar requested changes
Route definition missing

2017-01-28 16:46 UTC, lotar requested changes

2017-01-28 16:46 UTC, lotar commented on app/Http/routes.php
> +        Route::get('upload/{id}', 'FileUploadController@getProjectUploads');
Didn't we say to have *just* the route for project uploads deletion?

2017-01-28 16:46 UTC, lotar commented on app/Http/routes.php
> +        Route::delete('upload/{id}', 'FileUploadController@deleteProjectUploads');
make the route path to be `uploads/{projectId}/project`

2017-01-29 20:09 UTC, lotar approved these changes

2017-02-02 10:20 UTC, lotar commented
Why is this closed / branch deleted - it's not merged

2017-02-02 10:43 UTC, mvoloder commented
restored deleted branch, resolved conflicts

2017-02-02 10:44 UTC, merged